### ISSUE TITLE
Cannot register as DRep

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1591]
## Context & versions

1. GovTool - sancho-v1.0.9-dev
2. Cardano node - v9
3. Db-sync - 5.1.0
4. CSL - 12.0.0-beta.2

## Steps to reproduce

1. Try to register as a DRep

## Actual behavior

1. Sending transaction fails on missing expected deposit.

Error log from console:
```
Error: (400)
failed:
e6a027d422c6919ea3df6c375ec089ce6742e684d76a25a67ec70815308e2817
The deposit (resp. refund) specified in a stake credential or drep registration (resp. de-registration) does not match the value expected by the protocol. The field 'data.expectedDeposit', when present, indicates the deposit amount as currently expected by ledger.
Data: {"providedDeposit":{"ada":{"lovelace":0}},"expectedDeposit":{"ada":{"lovelace":500000000}}}

    at getTxSendError (dom.js:2547:12)
    at Object.submitTx (dom.js:2344:13)
    at async index-e86f2817.js:408:34682
    at async index-e86f2817.js:454:142445 'error'
```

## Expected behavior

1. Transaction succeeds

**Comment by MSzalowski** [comment]
# Additional note

After providing expected deposit value, there is another error on submitting transaction:
```Error: (400)
failed:
685e459a2936a677ff29adf37391a1a7b688d56134178acc8a97e62304453845
The transaction references an unknown stake credential. For example, to delegate to a stake pool, you must first register the stake key or script used for delegation. This may be done in the same transaction or in an earlier transaction but cannot happen retro-actively. The field 'data.unknownCredential' indicates what credential is used without being registered.
Data: {"unknownCredential":"ccf6ffabac700363af242c39fee6228e3a53b5fc7dae4c5675af8904"}

    at getTxSendError (dom.js:2547:12)
    at Object.submitTx (dom.js:2344:13)
    at async wallet.tsx:568:24
    at async RegisterAsDirectVoter.tsx:51:22
    ```

**Comment by Ryun1** [comment]
Can you share the Hex of the transaction?

I believe eternl is having an issue with the stake key registration they are adding an extra witness, which unbalances the transaction

**Comment by MSzalowski** [comment]
# Summary

Protocol params
```json
{
    "block_id": 1724530,
    "coins_per_utxo_size": 4310,
    "collateral_percent": 150,
    "committee_max_term_length": 0,
    "committee_min_size": 0,
    "cost_model_id": 400,
    "decentralisation": 0,
    "drep_activity": 0,
    "drep_deposit": 0,
    "dvt_committee_no_confidence": 0,
    "dvt_committee_normal": 0,
    "dvt_hard_fork_initiation": 0,
    "dvt_motion_no_confidence": 0,
    "dvt_p_p_economic_group": 0,
    "dvt_p_p_gov_group": 0,
    "dvt_p_p_network_group": 0,
    "dvt_p_p_technical_group": 0,
    "dvt_treasury_withdrawal": 0,
    "dvt_update_to_constitution": 0,
    "epoch_no": 399,
    "extra_entropy": null,
    "gov_action_deposit": 0,
    "gov_action_lifetime": 0,
    "id": 400,
    "influence": 0.3,
    "key_deposit": 2000000,
    "max_bh_size": 1100,
    "max_block_ex_mem": 62000000,
    "max_block_ex_steps": 20000000000,
    "max_block_size": 90112,
    "max_collateral_inputs": 3,
    "max_epoch": 18,
    "max_tx_ex_mem": 14000000,
    "max_tx_ex_steps": 10000000000,
    "max_tx_size": 16384,
    "max_val_size": 5000,
    "min_fee_a": 44,
    "min_fee_b": 155381,
    "min_fee_ref_script_cost_per_byte": 0,
    "min_pool_cost": 340000000,
    "min_utxo_value": 0,
    "monetary_expand_rate": 0.003,
    "nonce": "\\x207576bdd6d74392e1419cf248fb6a9d2f54a3fbb68072256324a4b4d45f5c53",
    "optimal_pool_count": 500,
    "pool_deposit": 500000000,
    "price_mem": 0.0577,
    "price_step": 0.0000721,
    "protocol_major": 10,
    "protocol_minor": 0,
    "pvt_committee_no_confidence": 0,
    "pvt_committee_normal": 0,
    "pvt_hard_fork_initiation": 0,
    "pvt_motion_no_confidence": 0,
    "pvtpp_security_group": 0,
    "treasury_growth_rate": 0.2
}
```

## Eternl wallet
Submission of a transaction using protocol params `drep_deposit` **0**:
**Signed transaction hex**
```
84a4008182582097df8b459218ce44720ee78809b26b4ca7b2ad523842b1b5fc4313c453df95ca02018282583900e0051448859b6c0bf8fb85593675074bbcb1b5cc910e39230b43e651ccf6ffabac700363af242c39fee6228e3a53b5fc7dae4c5675af89041a000f424082583900e0051448859b6c0bf8fb85593675074bbcb1b5cc910e39230b43e651ccf6ffabac700363af242c39fee6228e3a53b5fc7dae4c5675af89041b00000002e8cb37db021a0002cb95048382008200581cccf6ffabac700363af242c39fee6228e3a53b5fc7dae4c5675af890484108200581c66d1f9996f4f1b125d0797c1087840ac2f5422d97cb1b4470e29519300f683098200581cccf6ffabac700363af242c39fee6228e3a53b5fc7dae4c5675af89048200581c66d1f9996f4f1b125d0797c1087840ac2f5422d97cb1b4470e295193a100838258207ed71c7f35c84c82f47b3c12bdb103874f34d8997649cf17581da35eb85c492a5840a43ed0a29a07efbbc387f778f1ac3b0238daef27829335d2ae7c1aab4d17158e395a6be7b5ccce206a0078120ac3b996f61dfda66173cb6a67599b3cd67c1f028258201427799495a61589231c27834cd9d84a21533a002f5f6e6ba13f2cbe1b7c1e4f584095ee4ce88964499ee10afa9875fa8dee56b26672efd6f03d0b4ab48f6a7c579938472d316e0bed577a774f1478d0d5362d71f10c02a6e1e1dab055a6f8a11409825820b3c1941b4c746ec777ead4616a913ff580314dd8aa8b35f10bbd996590fb0dc5584048c3b995bcf062150a270f237668a19cb8b15c3119bdf0e0660dc91cbb2b1ee89fb5451e56470ddce2245de75249487573e27720c547f0b9a454ecb3a796bf03f5f6
```

**Error log** :red_circle: 
```
Error: (400)
failed:
065442f4291b01c5a5c2855c968f84ec9cbdbe02fcbb2c2f35f31c6918a22b78
The deposit (resp. refund) specified in a stake credential or drep registration (resp. de-registration) does not match the value expected by the protocol. The field 'data.expectedDeposit', when present, indicates the deposit amount as currently expected by ledger.
Data: {"providedDeposit":{"ada":{"lovelace":0}},"expectedDeposit":{"ada":{"lovelace":500000000}}}
```

Submission of a transaction using expected `drep_deposit` **500000000**:
**Signed transaction hex**
```
84a4008182582097df8b459218ce44720ee78809b26b4ca7b2ad523842b1b5fc4313c453df95ca02018282583900e0051448859b6c0bf8fb85593675074bbcb1b5cc910e39230b43e651ccf6ffabac700363af242c39fee6228e3a53b5fc7dae4c5675af89041a000f424082583900e0051448859b6c0bf8fb85593675074bbcb1b5cc910e39230b43e651ccf6ffabac700363af242c39fee6228e3a53b5fc7dae4c5675af89041b00000002cb1c5c83021a0002c66d048284108200581c66d1f9996f4f1b125d0797c1087840ac2f5422d97cb1b4470e2951931a1dcd6500f683098200581cccf6ffabac700363af242c39fee6228e3a53b5fc7dae4c5675af89048200581c66d1f9996f4f1b125d0797c1087840ac2f5422d97cb1b4470e295193a100838258207ed71c7f35c84c82f47b3c12bdb103874f34d8997649cf17581da35eb85c492a5840841ded7f0a324918d95f877c87b9cff13f9c3a3a4656a6422f6a830c08aa61b436a93b4d9d44f1a0cee70361eff62c3fc12b4deaf99e52e959eee08786627701825820b3c1941b4c746ec777ead4616a913ff580314dd8aa8b35f10bbd996590fb0dc55840e3d80e8c6040e63abbc648a267ff824f1e5596cd1b6bfa7a3208505f6e1637d15938be0ccf4f97f7e235f94bf7c2343d30156e8a579baeaa018f90e83016df0e8258201427799495a61589231c27834cd9d84a21533a002f5f6e6ba13f2cbe1b7c1e4f58406e448e35a421ba36c44063d8eaf2fe6033c5bff61f4540b2c4d1ef50b104117c50b6d650cb2e31b95a9a32010bcaba15b5fc3987b5f4d67f1c227b83f9287a02f5f6
```

**Error log** :red_circle: 
```
Error: (400)
failed:
fe509798fed930eb596b642bc530457f966bfd5cc7b7b71053ef2b96bcf74505
The transaction references an unknown stake credential. For example, to delegate to a stake pool, you must first register the stake key or script used for delegation. This may be done in the same transaction or in an earlier transaction but cannot happen retro-actively. The field 'data.unknownCredential' indicates what credential is used without being registered.
Data: {"unknownCredential":"ccf6ffabac700363af242c39fee6228e3a53b5fc7dae4c5675af8904"}
```
Q: Should we add the stake key to a drep registration certificate, like in the vote certs?

## Demos wallet (1.8.2)
Submission of a transaction using protocol params `drep_deposit` **0**:
**Signed transaction hex**
```
84a400818258209f9a6a57684bc7b61bdec6172eda122aee125a1e97662c6e329332fa2578c790010182825839008a8b7c47f3cf76b402a8133560e2208774a2c04c2b2c30a2a152478996590188c372dc1844364432db39b9bf16a8a2389fea7e7f2f29516a1a000f4240825839008a8b7c47f3cf76b402a8133560e2208774a2c04c2b2c30a2a152478996590188c372dc1844364432db39b9bf16a8a2389fea7e7f2f29516a1a1dc7f0e6021a0002c50d048284108200581c0b3db163792cb55d89d8326a427483eb42cae94671af869ecfe46ba600f683098200581c96590188c372dc1844364432db39b9bf16a8a2389fea7e7f2f29516a8200581c0b3db163792cb55d89d8326a427483eb42cae94671af869ecfe46ba6a10083825820f40cb1d01d4ad4ae547f0f9963dd773ed52ca9e092d877742c35a89bca74e6285840b4f162298b5944836d5c20a1cda6c5aa9efad6fda313b430d78f928d30c7104d0412d9c4b28d1697ec34bd49ca82d029047ba0097f6c9eb4f14aafad940d8509825820a3273a043fecdf38a8048c1908640e0e5f21d9d3a3825984f962d71ee1aaca2a5840bfe6f0edc628a238ab6719e56272988e932325ab6bb316012e47a49184c42b01924bdb70c9d64cd99675f8fc910b53a0d5d7fddacad9a84252c4d7e6debe900d8258202484fe2cd57ea93e3c3016bdef728ec39de07643847106a2630e2917222ab16758407d0397c34d6e64f2d4bb68d44bf839e3496da62acf3e65e2fb45daefbe32912fe967e2300d5a13339a4d6d4a3042c7814528a526087adf60b92e5dcc85c07c08f5f6
```

**Error log** :red_circle: 
```
{"contents":{"contents":{"contents":{"era":"ShelleyBasedEraConway","error":["ConwayUtxowFailure (UtxoFailure (ValueNotConservedUTxO (MaryValue (Coin 500824115) (MultiAsset (fromList []))) (MaryValue (Coin 1000824115) (MultiAsset (fromList [])))))","ConwayCertsFailure (CertFailure (GovCertFailure (ConwayDRepIncorrectDeposit (Coin 0) (Coin 500000000))))"],"kind":"ShelleyTxValidationError"},"tag":"TxValidationErrorInCardanoMode"},"tag":"TxCmdTxSubmitValidationError"},"tag":"TxSubmitFail"}
```

Submission of a transaction using expected `drep_deposit` **500000000**:
**Signed transaction hex**
```
84a40081825820abe4f870a923915564d69e2277f6f84882d5474bbcd2f5c766894148bca8ebce010182825839008a8b7c47f3cf76b402a8133560e2208774a2c04c2b2c30a2a152478996590188c372dc1844364432db39b9bf16a8a2389fea7e7f2f29516a1a000f4240825839008a8b7c47f3cf76b402a8133560e2208774a2c04c2b2c30a2a152478996590188c372dc1844364432db39b9bf16a8a2389fea7e7f2f29516a1b0000000b4a6cd188021a0002c66d048284108200581c0b3db163792cb55d89d8326a427483eb42cae94671af869ecfe46ba61a1dcd6500f683098200581c96590188c372dc1844364432db39b9bf16a8a2389fea7e7f2f29516a8200581c0b3db163792cb55d89d8326a427483eb42cae94671af869ecfe46ba6a10083825820f40cb1d01d4ad4ae547f0f9963dd773ed52ca9e092d877742c35a89bca74e62858406b2a5e01ac3eb1371c91d760b2e32a6ca13f83b32576f2619a1090d16f2ac910d5b7af5b56aa7ba7c19495a9da9751721029139b1b866eecd43f3cf5b7747802825820a3273a043fecdf38a8048c1908640e0e5f21d9d3a3825984f962d71ee1aaca2a58401c0742eab0f01500b06a751169bc3aa9bdfc81e239df9fda7c32bc13720b132ad767871a60ca0c67a994811ffc87e72f5fb028af240991b197c1c18020b8350a8258202484fe2cd57ea93e3c3016bdef728ec39de07643847106a2630e2917222ab1675840490d65b3461611013346cb544d9141a38c8447e0ca0f830d6460be5783973f252397435cc99e21f704e9bf0c14b9131efedd153f966701426a455dd93f7ea907f5f6
```

No error log, as this transaction succeeds :green_circle: :

**Comment by Ryun1** [comment]
I really appreciate the level of detail provided here, this is great.

A couple things seem to be going on here;
- DBSync seems to be incorrectly reporting the current protocol parameters, specifically it seems like a lot of the governance parameters are being reported as 0.
  - I have verified via my local node that this is incorrect (and as youve shown with your transactions this is incorrect)
  - I have raised [DB-Sync Issue 1777](https://github.com/IntersectMBO/cardano-db-sync/issues/1777)

- Eternl wallet is failing with the Stake key registration that is also taking place within that transaction
