### ISSUE TITLE
🐛 Deep link (Shared Link) of Governance Action does not work

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1801]
### Area

Voting Pillar

### Domain

sanchogov.tools

### Which wallet were you using?

Not relevant

### Context

Loading a governance action page by URL is leads to a blank page. However, the page loads correctly when going through the GovTool governance page.

This breaks any other third party tools linking the GovTool governance actions.

### Steps to reproduce

1. Open in incognito mode the following URL:
https://sanchogov.tools/governance_actions/3f52a04530e867db15a89ecde829a33bb35af939e5b043002b9fdc1ee4dee954#0

2. The page shown is a blank screen.
3. Check the console log, it shows the following stacktrace
```javascript
index-b0fff2a5.js:90 TypeError: Cannot read properties of undefined (reading 'proposal')
    at P6i (index-b0fff2a5.js:455:135181)
    at fu0 (index-b0fff2a5.js:38:17974)
    at dX2 (index-b0fff2a5.js:40:44769)
    at lX2 (index-b0fff2a5.js:40:40396)
    at MG4 (index-b0fff2a5.js:40:40319)
    at Z00 (index-b0fff2a5.js:40:40167)
    at Fc0 (index-b0fff2a5.js:40:36434)
    at sX2 (index-b0fff2a5.js:40:35371)
    at E2 (index-b0fff2a5.js:25:1693)
    at MessagePort.ie (index-b0fff2a5.js:25:2092)
```
4. Visiting the URL from the govenance_actions page works
a) visit https://sanchogov.tools/governance_actions
b)  Select the No confidence gov action with given ID. At the moment of writing on sanchonet, there is only one such gov action shown.
c) The page shows correctly.

### Actual behavior

The individual governance action page does not load by using the URL. Here is the stacktrace:
```javascript
index-b0fff2a5.js:90 TypeError: Cannot read properties of undefined (reading 'proposal')
    at P6i (index-b0fff2a5.js:455:135181)
    at fu0 (index-b0fff2a5.js:38:17974)
    at dX2 (index-b0fff2a5.js:40:44769)
    at lX2 (index-b0fff2a5.js:40:40396)
    at MG4 (index-b0fff2a5.js:40:40319)
    at Z00 (index-b0fff2a5.js:40:40167)
    at Fc0 (index-b0fff2a5.js:40:36434)
    at sX2 (index-b0fff2a5.js:40:35371)
    at E2 (index-b0fff2a5.js:25:1693)
    at MessagePort.ie (index-b0fff2a5.js:25:2092)
```

### Expected behavior

- The page loads correctly and shows the governance action details.
- No errors logged on the console.

**Comment by MSzalowski** [comment]
@jdyczka I've reassigned it to you as I can see that you've already fixed that partially within 96e6674a592722efc8d730c8822c888484957f08
