### ISSUE TITLE
🐛 Submission of Treasury Gov action fails

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#2447]
### Area

Proposal Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Eternal

### Context

Submitting a treasury withdrawal proposal as Gov Action currently fails with the following console log.
```javascript
index-bf5a9cfe.js:90 TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.buildTreasuryGovernanceAction (index-bf5a9cfe.js:414:50234)
    at app.cjs-df80b02d.js:139:140290
    at M2 (app.cjs-df80b02d.js:85:12569)
    at Generator.<anonymous> (app.cjs-df80b02d.js:85:14053)
    at Generator.next (app.cjs-df80b02d.js:85:13032)
    at _s2 (app.cjs-df80b02d.js:85:10225)
    at F (app.cjs-df80b02d.js:85:10436)
```

Here is a screenshot of submission:
<img width="1440" alt="Screenshot 2024-11-29 at 15 05 16" src="https://github.com/user-attachments/assets/43787613-af69-4f21-9b3d-9996921b8eae">

### Steps to reproduce

1. Create a normal treasury withdrawal proposal
2. From the proposal, try submitting as Governance action
3. Follow the guided form to download and host the metadata data.jsonld and fill in the metadata URL
4. Click submit to submit the govenance action.
5. Nothing happens on the UI after the progress spinner disappears.
6. Check console

### Actual behavior

Submission of the treasury withdrawal proposal as governance action leads to a progress spinner which disappears and nothing happens.

### Expected behavior

User should have been asked to sign the transaction and the treasury withdrawal governance action should have been successfully submitted.

**Comment by MSzalowski** [comment]
That is on the pillar side.

API of the builder has changed to support multiple addresses which is not yet supported in pdf-ui-v0.5.1.

Here is the documentation on how to build that transaction:
https://github.com/IntersectMBO/govtool/wiki/How-to-submit-a-Governance-Action-using-GovTool
